.ALIASES
V_V1            V1(+=N00206 -=0 ) CN @BB_BUCK.zener_diode(sch_1):INS228@SOURCE.VDC.Normal(chips)
D_D3            D3(A=0 K=N00103 ) CN @BB_BUCK.zener_diode(sch_1):INS76@DIODE.1N4744A.Normal(chips)
D_D2            D2(A=N00187 K=N00103 ) CN @BB_BUCK.zener_diode(sch_1):INS60@DIODE.1N4744A.Normal(chips)
R_R2            R2(1=N00187 2=0 ) CN @BB_BUCK.zener_diode(sch_1):INS158@ANALOG.R.Normal(chips)
R_R1            R1(1=N00206 2=N00187 ) CN @BB_BUCK.zener_diode(sch_1):INS142@ANALOG.R.Normal(chips)
.ENDALIASES
