.ALIASES
V_V1            V1(+=N14183 -=0 ) CN @LOW_PASS_FILTER.pi_filter(sch_1):INS14163@SOURCE.VAC.Normal(chips)
C_C30           C30(1=N14038 2=N143881 ) CN @LOW_PASS_FILTER.pi_filter(sch_1):INS14378@ANALOG.C.Normal(chips)
R_R2            R2(1=N14183 2=N14038 ) CN @LOW_PASS_FILTER.pi_filter(sch_1):INS15545@ANALOG.R.Normal(chips)
R_R3            R3(1=0 2=N143881 ) CN @LOW_PASS_FILTER.pi_filter(sch_1):INS18531@ANALOG.R.Normal(chips)
.ENDALIASES
